apiVersion: v2
name: platform
version: 1.0.0
appVersion: "1.0.0"
description: Umbrella chart for the complete demo platform
type: application
keywords:
  - platform
  - demo
  - fullstack
maintainers:
  - name: Nikko
    email: nikko@example.com
dependencies:
  - name: frontend
    version: "1.0.0"
    repository: "file://../frontend"
    condition: frontend.enabled
  - name: backend-api
    version: "1.0.0"
    repository: "file://../backend-api"
    condition: backend-api.enabled
  - name: redis
    version: "1.0.0"
    repository: "file://../redis"
    condition: redis.enabled
  - name: postgresql
    version: "1.0.0"
    repository: "file://../postgresql"
    condition: postgresql.enabled
