apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "backend-api.fullname" . }}
  labels:
    {{- include "backend-api.labels" . | nindent 4 }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      {{- include "backend-api.selectorLabels" . | nindent 6 }}
