apiVersion: v2
name: redis
version: 1.0.0
appVersion: "7.2.4"
description: Redis cache for session and data caching
type: application
keywords:
  - redis
  - cache
  - database
maintainers:
  - name: Nikko
    email: nikko@example.com
